Error saving awfewe Level: 1 Job: 1000
java.lang.NullPointerException
	at net.server.audit.ThreadTracker.accessThreadTracker(ThreadTracker.java:243)
	at net.server.audit.locks.active.TrackerReentrantLock.unregisterLocking(TrackerReentrantLock.java:136)
	at net.server.audit.locks.active.TrackerReentrantLock.unlock(TrackerReentrantLock.java:83)
	at client.inventory.ItemFactory.saveItemsCommon(ItemFactory.java:279)
	at client.inventory.ItemFactory.saveItems(ItemFactory.java:72)
	at client.inventory.ItemFactory.saveItems(ItemFactory.java:68)
	at server.CashShop.save(CashShop.java:526)
	at client.MapleCharacter.saveCharToDB(MapleCharacter.java:7586)
	at net.server.worker.CharacterAutosaverWorker.run(CharacterAutosaverWorker.java:39)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

---------------------------------
Error trying to rollback awfewe
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4586)
	at client.MapleCharacter.saveCharToDB(MapleCharacter.java:7597)
	at net.server.worker.CharacterAutosaverWorker.run(CharacterAutosaverWorker.java:39)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

---------------------------------
